"""Initial migration

Revision ID: 163e0de02fb6
Revises: 
Create Date: 2026-09-04 00:14:49.989284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '163e0de02fb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    schema='dbo'
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['dbo.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dbo'
    )
    op.create_table('course_students',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['dbo.courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['dbo.users.id'], ),
    sa.PrimaryKeyConstraint('course_id', 'student_id'),
    schema='dbo'
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['dbo.courses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dbo'
    )
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['dbo.topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dbo'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('materials', schema='dbo')
    op.drop_table('topics', schema='dbo')
    op.drop_table('course_students', schema='dbo')
    op.drop_table('courses', schema='dbo')
    op.drop_table('users', schema='dbo')
    # ### end Alembic commands ###
